sonar.projectKey=Sazikoff_go-project-244
sonar.organization=sazikoff

# ======================
# 📦 ОСНОВНОЙ КОД
# ======================
sonar.sources=cmd,internal,gendiff.go

# ======================
# 🧪 ТЕСТЫ
# ======================
sonar.tests=.

# ======================
# 🚫 ИСКЛЮЧЕНИЯ
# ======================
sonar.exclusions=\
bin/**,\
coverage.out,\
demo.cast

# тестовые данные не анализируем как код
sonar.test.exclusions=testdata/**

# тесты явно как тесты
sonar.test.inclusions=**/*_test.go

# ======================
# 📊 COVERAGE
# ======================
sonar.go.coverage.reportPaths=coverage.out