sonar.projectKey=Sazikoff_go-project-244
sonar.organization=sazikoff

sonar.sources=.
sonar.tests=.

sonar.exclusions=\
bin/**,\
coverage.out,\
demo.cast,\
testdata/**

sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out